#ifndef WORLD_CONSTANTS_HPP
#define WORLD_CONSTANTS_HPP

constexpr const int CHUNK_SIZE = 16, CHUNK_HEIGHT = 16;
constexpr const int CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE, 
CHUNK_VOLUME = CHUNK_SIZE * CHUNK_HEIGHT * CHUNK_SIZE;

#endif